compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
fsdp_config: {}
deepspeed_config: {}
downcast_bf16: 'no'
dynamo_backend: 'NO'
machine_rank: 0
main_training_function: main
mixed_precision: no
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false