name: delete old unused container images
on:
  schedule:
    - cron: "0 13 * * 1" 
    # Every Monday at 1PM UTC (9AM EST)
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  clean-ghcr:
    strategy:
      matrix:
        IMAGE-NAME: [develop, develop_CUDA_11_8, develop_CUDA_12_3, develop_sif, develop_CUDA_11_8_sif, develop_CUDA_12_3_sif]
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ matrix.IMAGE-NAME }}
          cut-off: One week ago UTC
          keep-at-least: 3
          account-type: personal
          token: ${{ secrets.cleanup_packages }}
          token-type: pat
