# docker_action.yml
name: 'Build Docker image and container'
description: 'description'
inputs:
  test-to-run:  # id of input
    description: 'tests to run'
    required: true
    default: 'python -m pytest tests\test_ao.py'
outputs:
  test_results: # id of output
    description: 'did we pass'
runs:
  using: 'docker'
  image: /.github/Dockerfile
  args:
    - ${{ inputs.test-to-run }}
