name: MacOS-build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'
    tags:
      - '*'

jobs:
  build:
    name: Testing MacOS build
    runs-on: "macos-latest"
    defaults:
      run:
        shell: sh -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set cache date
        id: set-date
        run: echo "today=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/macos.txt') }}-${{ steps.set-date.outputs.today }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r macos.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test environment
        run: |
          pip list

#      - name: Test IO modules
#        run: python -m pytest -vvv tests/test_io.py
#
#      - name: Test embeddings modules
#        run: python -m pytest -vvv tests/test_embeddings.py
#
#      - name: Test AO modules
#        run: python -m pytest -vvv tests/test_ao.py