name: Ubuntu-build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'

jobs:
  build:
    name: Testing Ubuntu build
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ubuntu.yml
          activate-environment: ml
          auto-activate-base: false

      - name: Set cache date
        id: set-date
        run: echo "today=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA }}/envs
          key: ubuntu-build-${{ hashFiles('ubuntu.yml') }}-${{ env.DATE }}

      - name: Update environment
        run: conda env update -n ml -f ubuntu.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test environment
        run: |
          conda info
          conda list
          printenv

#      - name: Test IO modules
#        run: python -m pytest -vvv tests/test_io.py
#
#      - name: Test embeddings modules
#        run: python -m pytest -vvv tests/test_embeddings.py
#
#      - name: Test AO modules
#        run: python -m pytest -vvv tests/test_ao.py
