name: Windows-build

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'
    tags:
      - '*'

jobs:
  condaenv:
    name: win-64
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Building conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ml
          environment-file: macos.yml
          auto-activate-base: false

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: windows
          key: windows-conda-${{ hashFiles('windows.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
          id: cache

      - name: Update environment
        run: mamba env update -n ml -f windows.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Bash
        shell: bash -el {0}
        run: |
          conda info
          conda list

      - name: Test IO modules
        shell: bash -l {0}
        run: python -m pytest -vvv tests/test_io.py

      - name: Test embeddings modules
        shell: bash -l {0}
        run: python -m pytest -vvv tests/test_io.py

      - name: Test AO modules
        shell: bash -l {0}
        run: python -m pytest -vvv tests/test_io.py